"""Add is_guest field to users table

Revision ID: 0dd21eeff47b
Revises: a7025849f9a6
Create Date: 2025-11-20 12:56:46.052806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd21eeff47b'
down_revision: Union[str, Sequence[str], None] = 'a7025849f9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_guest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_guest')
    # ### end Alembic commands ###
